### ISSUE TITLE
Creat Spots Model, Migration and Seeder files

### ISSUE THREAD

**Issue by 360devin360** [360devin360/Sk8nBnB#32]
# Set up Spots Table
### Used for validation and creation of Spots values 
- [x] Use Sequelize to create a Model and Migration file for Spots using values specified in the API docs
- [x] Include options object for schema values
- [x] include reversal of actions in the async down function after async up function
### creates a relationship between the Users and Spots table
- [x] use Model.belongsTo method to associate Spots to Users by ownerId
## Create seed data to populate the Spots table data
- [x] add all the fields specified in the API docs
- [x] use a valid value for owner id

**Comment by AnthonyBronca** [comment]
Your spot tables was looking good at a first glance!
