### ISSUE TITLE
Create Reviews Model, Migration and Seeder Files

### ISSUE THREAD

**Issue by 360devin360** [360devin360/Sk8nBnB#33]
# Set up Reviews Table
### Used for validation and creation of Reviews values 
- [x] Use Sequelize to create a Model and Migration file for Reviews using values specified in the API docs
- [x] Include options object for schema values
- [x] include reversal of actions in the async down function after async up function
### creates a relationship between the reviews table and the Users and Spots tables
- [x] use Model.belongsTo method to associate Review to User by userId
- [x] use Model.belongsTo method to associate Review to Spot by spotId
## Create seed data to populate the Reviews table data
- [x] add all the fields specified in the API docs
- [x] use a valid values for userId and spotId

**Comment by AnthonyBronca** [comment]
Review tables was looking good! You may run into some issues with production if you do not add `options` or use `options.tableName = <table name>`. Something to note
