### ISSUE TITLE
Create Bookings Model, Migration and Seeder File

### ISSUE THREAD

**Issue by 360devin360** [360devin360/Sk8nBnB#34]
# Set up Bookings Table
### Used for validation and creation of Bookings values 
- [x] Use Sequelize to create a Model and Migration file for Bookings using values specified in the API docs
- [x] Include options object for schema values
- [x] include reversal of actions in the async down function after async up function
### creates a relationship between the Bookings table and the Users and Spots tables
- [x] use Model.belongsTo method to associate Booking to User by userId
- [x] use Model.belongsTo method to associate Booking to Spot by spotId
## Create seed data to populate the Bookings table data
- [x] add all the fields specified in the API docs
- [x] use a valid values for userId and spotId

**Comment by AnthonyBronca** [comment]
Looked Good but keep in mind the options portion, (look at my previous comments) as this may cause issues in production.
